import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { UserPlus, Building2, FileText, UserRoundPlus } from 'lucide-react'
import { TextField, MenuItem, FormControl, InputLabel, Select } from '@mui/material'
import { useAuth } from '../contexts/AuthContext'
import { useRequests } from '../contexts/RequestContext'
import { requestService } from '../services/requestService'
import { customerTypes, labelize, priorities, products, requestTypes, sources } from '../constants/requestConstants'
import { Toast } from '../components/common/Toast'

export function CreateRequestPage() {
 const {user}=useAuth(); const {customers,sites,refresh}=useRequests(); const navigate=useNavigate()
 const [customerId,setCustomerId]=useState(customers[0]?.id||''); const [newCustomer,setNewCustomer]=useState(false); const [customerName,setCustomerName]=useState(''); const [customerPhone,setCustomerPhone]=useState(''); const [customerType,setCustomerType]=useState('INDIVIDUAL'); const [company,setCompany]=useState('')
 const [siteId,setSiteId]=useState(''); const [newSite,setNewSite]=useState(false); const [siteName,setSiteName]=useState(''); const [source,setSource]=useState('GOOGLE_ADS'); const [requestType,setRequestType]=useState('NEW_ENQUIRY'); const [product,setProduct]=useState('UPVC_WINDOWS'); const [description,setDescription]=useState(''); const [quantity,setQuantity]=useState(''); const [expectedDate,setExpectedDate]=useState(''); const [priority,setPriority]=useState('MEDIUM'); const [remarks,setRemarks]=useState(''); const [toast,setToast]=useState('')
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!user||!description.trim())return;let cid=customerId;if(newCustomer){cid=crypto.randomUUID();const now=new Date().toISOString();const all=[...customers,{id:cid,name:customerName||'New Customer',companyName:company||undefined,customerType:customerType as any,phone:customerPhone||'—',createdAt:now}];localStorage.setItem('rk_customers',JSON.stringify(all))}let sid=siteId;if(newSite&&siteName){sid=crypto.randomUUID();const all=[...sites,{id:sid,customerId:cid,name:siteName,createdAt:new Date().toISOString()}];localStorage.setItem('rk_sites',JSON.stringify(all))}const r=requestService.create({customerId:cid,siteId:sid||undefined,createdBy:user.id,assignedTo:user.role==='ADMIN'?undefined:user.id,source:source as any,requestType:requestType as any,productCategory:product as any,description,quantity:quantity?Number(quantity):undefined,priority:priority as any,status:'NEW',expectedDate:expectedDate||undefined,remarks:remarks||undefined},user.id);refresh();setToast(`Request ${r.requestNumber} created successfully`);setTimeout(()=>navigate(`/requests/${r.id}`),700)}
 return <div><div className="page-heading"><div><p className="eyebrow">NEW WORK ITEM</p><h1>Create Request</h1><p className="muted">Capture the customer, project and sales requirement in one flow.</p></div></div>
 <form onSubmit={submit} className="request-form"><section className="form-section panel"><div className="form-section-title"><div className="section-icon"><UserPlus size={19}/></div><div><h3>Customer</h3><p>Select an existing customer or create a new one.</p></div><button type="button" className="secondary-button ml-auto" onClick={()=>setNewCustomer(!newCustomer)}><UserRoundPlus size={16}/>{newCustomer?'Use Existing':'Create New'}</button></div>{!newCustomer?<FormControl fullWidth size="small"><InputLabel>Existing customer</InputLabel><Select label="Existing customer" value={customerId} onChange={e=>setCustomerId(e.target.value)}>{customers.map(c=><MenuItem key={c.id} value={c.id}>{c.companyName||c.name} · {labelize(c.customerType)}</MenuItem>)}</Select></FormControl>:<div className="form-grid"><TextField label="Customer name" required value={customerName} onChange={e=>setCustomerName(e.target.value)}/><TextField label="Company name" value={company} onChange={e=>setCompany(e.target.value)}/><TextField label="Phone" required value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)}/><FormControl size="small"><InputLabel>Customer type</InputLabel><Select label="Customer type" value={customerType} onChange={e=>setCustomerType(e.target.value)}>{customerTypes.map(x=><MenuItem key={x} value={x}>{labelize(x)}</MenuItem>)}</Select></FormControl></div>}</section>
 <section className="form-section panel"><div className="form-section-title"><div className="section-icon"><Building2 size={19}/></div><div><h3>Site / Project</h3><p>Optional project association for this request.</p></div><button type="button" className="secondary-button ml-auto" onClick={()=>setNewSite(!newSite)}>{newSite?'Use Existing':'Create New'}</button></div>{newSite?<TextField label="Site / project name" value={siteName} onChange={e=>setSiteName(e.target.value)} fullWidth/>:<FormControl fullWidth size="small"><InputLabel>Existing site / project</InputLabel><Select label="Existing site / project" value={siteId} onChange={e=>setSiteId(e.target.value)}><MenuItem value="">No site / project</MenuItem>{sites.filter(s=>!customerId||s.customerId===customerId).map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select></FormControl>}</section>
 <section className="form-section panel"><div className="form-section-title"><div className="section-icon"><FileText size={19}/></div><div><h3>Request details</h3><p>Describe the requirement and its current priority.</p></div></div><div className="form-grid"><FormControl size="small"><InputLabel>Source</InputLabel><Select label="Source" value={source} onChange={e=>setSource(e.target.value)}>{sources.map(x=><MenuItem key={x} value={x}>{labelize(x)}</MenuItem>)}</Select></FormControl><FormControl size="small"><InputLabel>Request type</InputLabel><Select label="Request type" value={requestType} onChange={e=>setRequestType(e.target.value)}>{requestTypes.map(x=><MenuItem key={x} value={x}>{labelize(x)}</MenuItem>)}</Select></FormControl><FormControl size="small"><InputLabel>Product category</InputLabel><Select label="Product category" value={product} onChange={e=>setProduct(e.target.value)}>{products.map(x=><MenuItem key={x} value={x}>{labelize(x)}</MenuItem>)}</Select></FormControl><TextField label="Quantity" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/><TextField label="Expected date" type="date" InputLabelProps={{shrink:true}} value={expectedDate} onChange={e=>setExpectedDate(e.target.value)}/><FormControl size="small"><InputLabel>Priority</InputLabel><Select label="Priority" value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(x=><MenuItem key={x} value={x}>{labelize(x)}</MenuItem>)}</Select></FormControl></div><TextField label="Description" required multiline minRows={4} fullWidth value={description} onChange={e=>setDescription(e.target.value)} placeholder="What does the customer need?"/><TextField label="Remarks" multiline minRows={2} fullWidth value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Optional internal notes"/></section>
 <div className="form-actions"><button type="button" className="secondary-button" onClick={()=>navigate(-1)}>Cancel</button><button className="primary-button">Create Request</button></div></form>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</div>
}