import { useMemo, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { ArrowLeft, Pencil, UserRound, CalendarDays, MessageSquare, Paperclip, Send, Trash2, Download, Clock3 } from 'lucide-react'
import { FormControl, InputLabel, MenuItem, Select, Dialog, DialogTitle, DialogContent, DialogActions, Button } from '@mui/material'
import { useAuth } from '../contexts/AuthContext'
import { useRequests } from '../contexts/RequestContext'
import { requestService } from '../services/requestService'
import { labelize, statuses } from '../constants/requestConstants'
import { StatusBadge, PriorityBadge } from '../components/common/StatusBadge'
import { EmptyState } from '../components/common/EmptyState'
import { Toast } from '../components/common/Toast'

export function RequestDetailPage() {
 const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();const {requests,customers,sites,activities,documents,refresh}=useRequests();const r=requests.find(x=>x.id===id)
 const [comment,setComment]=useState('');const [statusOpen,setStatusOpen]=useState(false);const [assignOpen,setAssignOpen]=useState(false);const [newStatus,setNewStatus]=useState(r?.status||'NEW');const [assignee,setAssignee]=useState(r?.assignedTo||'');const [toast,setToast]=useState('')
 const c=customers.find(x=>x.id===r?.customerId);const site=sites.find(x=>x.id===r?.siteId);const users=JSON.parse(localStorage.getItem('rk_users')||'[]');const acts=useMemo(()=>activities.filter(a=>a.requestId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[activities,id]);const docs=documents.filter(d=>d.requestId===id)
 if(!r||!user)return <EmptyState title="Request not available" text="This request may not exist or you may not have access to it."/>
 const canView=user.role==='ADMIN'||r.createdBy===user.id||r.assignedTo===user.id
 if(!canView)return <EmptyState title="Access denied" text="You do not have permission to view this request."/>
 const doComment=()=>{if(!comment.trim())return;requestService.comment(r.id,user.id,comment);setComment('');refresh();setToast('Comment added')}
 const doStatus=()=>{requestService.status(r.id,newStatus as any,user.id);refresh();setStatusOpen(false);setToast('Status updated successfully')}
 const doAssign=()=>{if(!assignee)return;requestService.assign(r.id,assignee,user.id);refresh();setAssignOpen(false);setToast('Request assignment updated')}
 const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){requestService.addDocument(r.id,user.id,f);refresh();setToast('Document metadata saved')}}
 return <div><button className="back-button" onClick={()=>navigate('/requests')}><ArrowLeft size={17}/> Back to requests</button><div className="detail-hero"><div><p className="eyebrow">{r.requestNumber}</p><h1>{c?.companyName||c?.name}</h1><p className="muted">{site?.name||'No site / project'} · Created {new Date(r.createdAt).toLocaleDateString('en-IN')}</p></div><div className="detail-actions"><StatusBadge status={r.status}/><PriorityBadge priority={r.priority}/><button className="secondary-button" onClick={()=>navigate(`/requests/${r.id}/edit`)}><Pencil size={16}/> Edit</button><button className="primary-button" onClick={()=>setStatusOpen(true)}>Change status</button>{user.role==='ADMIN'&&<button className="secondary-button" onClick={()=>setAssignOpen(true)}><UserRound size={16}/> Assign</button>}</div></div>
 <div className="detail-grid"><div className="detail-main"><section className="panel info-card"><div className="panel-header"><div><h3>Request information</h3><p>Customer and requirement details</p></div></div><div className="info-grid"><div><span>Customer</span><strong>{c?.name}</strong></div><div><span>Customer type</span><strong>{labelize(c?.customerType)}</strong></div><div><span>Company</span><strong>{c?.companyName||'—'}</strong></div><div><span>Phone</span><strong>{c?.phone||'—'}</strong></div><div><span>Source</span><strong>{labelize(r.source)}</strong></div><div><span>Request type</span><strong>{labelize(r.requestType)}</strong></div><div><span>Product</span><strong>{labelize(r.productCategory)}</strong></div><div><span>Quantity</span><strong>{r.quantity??'—'}</strong></div><div><span>Expected date</span><strong>{r.expectedDate||'—'}</strong></div><div><span>Assigned to</span><strong>{users.find((u:any)=>u.id===r.assignedTo)?.displayName||'Unassigned'}</strong></div></div><div className="description-box"><span>Description</span><p>{r.description}</p>{r.remarks&&<><span>Remarks</span><p>{r.remarks}</p></>}</div></section>
 <section className="panel comment-card"><div className="panel-header"><div><h3>Comments</h3><p>Add a note to the request timeline.</p></div></div><div className="comment-input"><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Write a customer update, requirement or internal note..."/><button className="primary-button" onClick={doComment}><Send size={16}/> Add comment</button></div></section>
 <section className="panel documents-card"><div className="panel-header"><div><h3>Documents</h3><p>Demo metadata is stored locally in your browser.</p></div><label className="secondary-button upload-label"><Paperclip size={16}/> Upload<input type="file" hidden onChange={upload}/></label></div>{docs.length?docs.map(d=><div className="document-row" key={d.id}><div className="doc-icon"><Paperclip size={18}/></div><div><strong>{d.fileName}</strong><span>{d.contentType} · {(d.size/1024).toFixed(1)} KB · {new Date(d.uploadedAt).toLocaleDateString('en-IN')}</span></div><div className="doc-actions"><button className="row-action"><Download size={15}/></button><button className="row-action danger" onClick={()=>{requestService.deleteDocument(d.id,user.id);refresh()}}><Trash2 size={15}/></button></div></div>):<EmptyState title="No documents attached" text="Upload a document to add it to the request."/>}</section></div>
 <aside className="detail-side"><section className="panel"><div className="panel-header"><div><h3>Timeline</h3><p>Newest activity first</p></div><Clock3 size={18}/></div><div className="timeline">{acts.length?acts.map(a=><div className="timeline-item" key={a.id}><div className="timeline-dot"/><div><div className="timeline-meta">{users.find((u:any)=>u.id===a.userId)?.displayName||'User'} · {new Date(a.createdAt).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</div><p>{a.description}</p>{a.type==='STATUS_CHANGED'&&<span className="timeline-change">{labelize(a.oldValue)} → {labelize(a.newValue)}</span>}</div></div>):<EmptyState title="No activity recorded" text="Activity will appear as the request changes."/>}</div></section></aside></div>
 <Dialog open={statusOpen} onClose={()=>setStatusOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Change status</DialogTitle><DialogContent><FormControl fullWidth sx={{mt:1}}><InputLabel>New status</InputLabel><Select label="New status" value={newStatus} onChange={e=>setNewStatus(e.target.value)}>{statuses.map(s=><MenuItem key={s} value={s}>{labelize(s)}</MenuItem>)}</Select></FormControl></DialogContent><DialogActions><Button onClick={()=>setStatusOpen(false)}>Cancel</Button><Button variant="contained" onClick={doStatus}>Update Status</Button></DialogActions></Dialog>
 <Dialog open={assignOpen} onClose={()=>setAssignOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Assign request</DialogTitle><DialogContent><FormControl fullWidth sx={{mt:1}}><InputLabel>Sales user</InputLabel><Select label="Sales user" value={assignee} onChange={e=>setAssignee(e.target.value)}>{users.filter((u:any)=>u.role==='SALES_USER').map((u:any)=><MenuItem key={u.id} value={u.id}>{u.displayName}</MenuItem>)}</Select></FormControl></DialogContent><DialogActions><Button onClick={()=>setAssignOpen(false)}>Cancel</Button><Button variant="contained" onClick={doAssign}>Assign</Button></DialogActions></Dialog>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</div>
}