import { useMemo, useState } from 'react'
import { useSearchParams, useNavigate } from 'react-router-dom'
import { Search, SlidersHorizontal, X, Eye, Pencil } from 'lucide-react'
import { MenuItem, Select, FormControl, InputLabel, TextField } from '@mui/material'
import { useAuth } from '../contexts/AuthContext'
import { useRequests } from '../contexts/RequestContext'
import { StatusBadge, PriorityBadge } from '../components/common/StatusBadge'
import { labelize, priorities, sources, statuses } from '../constants/requestConstants'
import { EmptyState } from '../components/common/EmptyState'

export function RequestsPage() {
 const {user}=useAuth(); const {requests,customers,sites}=useRequests(); const navigate=useNavigate(); const [params]=useSearchParams()
 const [search,setSearch]=useState(''); const [status,setStatus]=useState(params.get('status')||''); const [priority,setPriority]=useState(''); const [source,setSource]=useState(''); const [sort,setSort]=useState('updated')
 const visible=useMemo(()=>requests.filter(r=>user?.role==='ADMIN'||r.createdBy===user?.id||r.assignedTo===user?.id).filter(r=>{const c=customers.find(x=>x.id===r.customerId);const q=search.toLowerCase();return (!q||r.requestNumber.toLowerCase().includes(q)||c?.name.toLowerCase().includes(q)||c?.companyName?.toLowerCase().includes(q))&&(!status||r.status===status)&&(!priority||r.priority===priority)&&(!source||r.source===source)}).sort((a,b)=>sort==='created'?b.createdAt.localeCompare(a.createdAt):b.updatedAt.localeCompare(a.updatedAt)),[requests,user,customers,search,status,priority,source,sort])
 const clear=()=>{setSearch('');setStatus('');setPriority('');setSource('')}
 return <div><div className="page-heading"><div><p className="eyebrow">WORKSPACE</p><h1>{user?.role==='ADMIN'?'All Requests':'My Requests'}</h1><p className="muted">{visible.length} visible requests</p></div><button className="primary-button" onClick={()=>navigate('/requests/new')}>+ New Request</button></div>
 <section className="panel"><div className="filters"><div className="search-box"><Search size={18}/><input placeholder="Search request, customer or company..." value={search} onChange={e=>setSearch(e.target.value)}/></div><FormControl size="small"><InputLabel>Status</InputLabel><Select label="Status" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="">All statuses</MenuItem>{statuses.map(s=><MenuItem key={s} value={s}>{labelize(s)}</MenuItem>)}</Select></FormControl><FormControl size="small"><InputLabel>Priority</InputLabel><Select label="Priority" value={priority} onChange={e=>setPriority(e.target.value)}><MenuItem value="">All priorities</MenuItem>{priorities.map(s=><MenuItem key={s} value={s}>{labelize(s)}</MenuItem>)}</Select></FormControl><FormControl size="small"><InputLabel>Source</InputLabel><Select label="Source" value={source} onChange={e=>setSource(e.target.value)}><MenuItem value="">All sources</MenuItem>{sources.map(s=><MenuItem key={s} value={s}>{labelize(s)}</MenuItem>)}</Select></FormControl><FormControl size="small"><InputLabel>Sort</InputLabel><Select label="Sort" value={sort} onChange={e=>setSort(e.target.value)}><MenuItem value="updated">Recently updated</MenuItem><MenuItem value="created">Recently created</MenuItem></Select></FormControl>{(search||status||priority||source)&&<button className="clear-filter" onClick={clear}><X size={16}/> Clear</button>}</div>
 <div className="table-scroll"><table className="requests-table"><thead><tr><th>Request</th><th>Customer</th><th>Site / Project</th><th>Source</th><th>Type</th><th>Product</th><th>Status</th><th>Priority</th><th>Assigned</th><th>Updated</th><th></th></tr></thead><tbody>{visible.map(r=>{const c=customers.find(x=>x.id===r.customerId);const s=sites.find(x=>x.id===r.siteId);const users=JSON.parse(localStorage.getItem('rk_users')||'[]');const ass=users.find((u:any)=>u.id===r.assignedTo)?.displayName;return <tr key={r.id}><td><strong>{r.requestNumber}</strong><small>{new Date(r.createdAt).toLocaleDateString('en-IN')}</small></td><td><strong>{c?.companyName||c?.name}</strong><small>{c?.name!==c?.companyName?c?.name:''}</small></td><td>{s?.name||'—'}</td><td>{labelize(r.source)}</td><td>{labelize(r.requestType)}</td><td>{labelize(r.productCategory)}</td><td><StatusBadge status={r.status}/></td><td><PriorityBadge priority={r.priority}/></td><td>{ass||'Unassigned'}</td><td>{new Date(r.updatedAt).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</td><td><button className="row-action" onClick={()=>navigate(`/requests/${r.id}`)}><Eye size={16}/></button><button className="row-action" onClick={()=>navigate(`/requests/${r.id}/edit`)}><Pencil size={15}/></button></td></tr>})}</tbody></table></div>{visible.length===0&&<EmptyState title="No requests found" text="Try changing your filters or create a new request."/>}</section></div>
}